adding srx security functions
DataKnox/nornir_pyez pull request #15
Opened 2020-12-21 13:42 UTC by packetferret

adding the following functionality for SRX firewalls

- validate status of IPsec connections (security associations for IKE and IPsec)
- retrieve security zones information
- retrieve security policies configured on the firewall
- retrieve source and destination NAT policies

2020-12-21 15:30 UTC, DataKnox requested changes
Good work, and thank you!
- removed pyez_int_terse from __init__ . Please add it back
- incorrect title on pyez_sec_nat_dest
- not enough = characters on pyez_sec_nat_dest.rst or pyez_sec_nat_src.rst titles. Think you need 1 more
- On pyez_sec_nat_dest and pyez_sec_nat_sec , does it have to have the all=True arg? Would it be better to create a dict and pass it in as an option? See pyez_rpc https://github.com/DataKnox/nornir_pyez/blob/main/nornir_pyez/plugins/tasks/pyez_rpc.py

2020-12-22 00:31 UTC, packetferret commented
> * removed pyez_int_terse from **init** . Please add it back
> * incorrect title on pyez_sec_nat_dest
> * not enough = characters on pyez_sec_nat_dest.rst or pyez_sec_nat_src.rst titles. Think you need 1 more

acknowledged and corrected

> * On pyez_sec_nat_dest and pyez_sec_nat_sec , does it have to have the all=True arg? Would it be better to create a dict and pass it in as an option? See pyez_rpc https://github.com/DataKnox/nornir_pyez/blob/main/nornir_pyez/plugins/tasks/pyez_rpc.py

this is a good suggestion, let me know if you think my method is sufficient

2020-12-22 03:35 UTC, DataKnox approved these changes

2020-12-22 03:35 UTC, DataKnox commented
Approved and merging #15

2020-12-22 03:35 UTC, merged